# Generated by Django 3.1.2 on 2020-11-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0008_image_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='desk',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
