# Generated by Django 3.1.3 on 2020-11-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0011_auto_20201120_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
