# Generated by Django 5.1.4 on 2025-01-04 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0013_alter_comment_id_alter_image_id_alter_tag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('image', models.ImageField(upload_to='static/%y')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myaccount.category')),
            ],
        ),
    ]
