# Generated by Django 3.1.2 on 2020-10-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_auto_20201022_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=1000)),
                ('komentar', models.CharField(max_length=1000)),
            ],
        ),
    ]
