# Generated by Django 3.1.2 on 2020-10-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0004_coment'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='kategori',
            field=models.CharField(choices=[(' Horror Indo & Horror Luar Negri', 'Horror Indo & Horror Luar Negri'), (' Comedy Indo & Comedy Luar Negri ', ' Comedy Indo & Comedy Luar Negri '), (' Romance Indo & Romance Luar Negri', 'Romance Indo & Romance Luar Negri')], max_length=1000, null=True),
        ),
    ]
