# Generated by Django 3.1.2 on 2020-10-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0005_image_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=1000)),
                ('Komentar', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Coment',
        ),
    ]
