# Generated by Django 3.1.2 on 2020-10-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0006_auto_20201028_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='deskripsi',
            field=models.TextField(),
        ),
    ]
