# Generated by Django 3.1.2 on 2020-11-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0007_auto_20201029_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='button',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
