# Generated by Django 3.1.3 on 2020-11-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0010_auto_20201106_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostModel',
            new_name='Comments',
        ),
    ]
